//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cvDBEntities : DbContext
    {
        public cvDBEntities()
            : base("name=cvDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CvTablosu> CvTablosu { get; set; }
        public virtual DbSet<FakulteTablosu> FakulteTablosu { get; set; }
        public virtual DbSet<MezunTablosu> MezunTablosu { get; set; }
        public virtual DbSet<OkulTablosu> OkulTablosu { get; set; }
        public virtual DbSet<ReferansTablosu> ReferansTablosu { get; set; }
        public virtual DbSet<SehirTablosu> SehirTablosu { get; set; }
        public virtual DbSet<StajTablosu> StajTablosu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UyeTablosu> UyeTablosu { get; set; }
    }
}
