//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferansTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReferansTablosu()
        {
            this.CvTablosu = new HashSet<CvTablosu>();
        }
    
        public int ReferansId { get; set; }
        public string R_Adi { get; set; }
        public string R_Soyadi { get; set; }
        public string R_Meslek { get; set; }
        public string R_Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CvTablosu> CvTablosu { get; set; }
    }
}
