//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeTablosu
    {
        public int UyeId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Eposta { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> DogumT { get; set; }
        public string Telefon { get; set; }
        public string OlusturulmaT { get; set; }
    }
}
